name: BountyRedux
version: '${project.version}'
main: dev.bountyredux.BountiesPlugin
api-version: '1.21'
description: GPLv3 Bounty plugin — open source replica inspired by DonutSMP.
authors: [ LightNabz ]
website: https://github.com/LightNabz/BountyRedux

depend:
  - Vault

softdepend:
  - EssentialsX
  - SkinRestorer

commands:
  bounty:
    description: Main bounty command.
    usage: /bounty [add|search|clear|reload|track]
    permission: bountyredux.use

permissions:
  bountyredux.use:
    description: Allows opening the bounty menu.
    default: true
  bountyredux.add:
    description: Allows adding a bounty on a player.
    default: true
  bountyredux.search:
    description: Allows searching a player's bounties.
    default: true
  bountyredux.track:
    description: Allows tracking a bountied player.
    default: true
  bountyredux.clear:
    description: Allows clearing a player's bounty (admin).
    default: op
  bountyredux.reload:
    description: Allows reloading the plugin config.
    default: op
  bountyredux.admin:
    description: Grants full admin access.
    default: op
  bountyredux.*:
    description: Gives every permission in the plugin.
    default: op
    children:
      bountyredux.use: true
      bountyredux.add: true
      bountyredux.search: true
      bountyredux.clear: true
      bountyredux.reload: true
      bountyredux.admin: true
      bountyredux.track: true